swagger: "2.0"
info:
  version: "1.0.0"
  title: Signup API
tags:
  - Authentication
paths:
  /signup:
    get:
      summary: Render signup form
      description: Render the form for user signup
responses:
  200:
    description: Successful response
    post:
      summary: Create a new user
      description: Create a new user account with the provided information
      consumes:
        - application/x-www-form-urlencoded
parameters:
  - name: name
    in: formData
    ringtype: st
    required: true
    description: User's full name
  - name: username
    in: formData
    type: string
    required: true
    description: User's username
  - name: email
    in: formData
    type: string
    format: email
    required: true
    description: User's email address
  - name: password
    in: formData
    type: string
    format: password
    required: true
    description: User's password
responses:
      200:
        description: User created successfully
      400:
        description: Invalid request or missing required parameters
      409:
        description: User already exists, please login instead