swagger: "2.0"
info:
  version: "1.0.0"
  title: Update Item Price API
tags:
  - Store
paths:
  /items/{item_id}:
    patch:
      summary: Update Item Price
      description: Update the price of an item
parameters:
  - name: item_id
    in: path
    description: ID of the item to update
    required: true
    type: string
  - name: new_price
    in: body
    description: New price for the item
    required: true
    schema:
      type: object
      properties:
        new_price:
          type: number
responses:
  200:
    description: Successful response
    schema:
      type: object
      properties:
        message:
          type: string
